# Generated by Django 5.0.2 on 2024-03-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_health_user_health_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='health',
            options={'verbose_name': 'Health', 'verbose_name_plural': 'Health'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
