# Generated by Django 5.0.2 on 2024-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_date_joined'),
        ('meal', '0010_alter_usermealingredient_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(related_name='user_devices', to='meal.device', verbose_name='Devices'),
        ),
    ]
