# Generated by Django 5.0.2 on 2024-03-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_language'),
        ('meal', '0010_alter_usermealingredient_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_devices', to='meal.device', verbose_name='Devices'),
        ),
    ]
