# Generated by Django 5.0.2 on 2024-03-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/users', verbose_name='Image'),
        ),
    ]
