# Generated by Django 5.0.2 on 2024-03-02 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_health_user_health_status'),
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='health_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.health', verbose_name='Health status'),
        ),
        migrations.AddField(
            model_name='meal',
            name='health_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.health', verbose_name='Health status'),
        ),
    ]
