# Generated by Django 5.0.2 on 2024-03-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_ingredient_health_status_meal_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='media/images/devices', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='categories',
            field=models.ManyToManyField(related_name='ingredient_categories', to='meal.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='tags',
            field=models.ManyToManyField(related_name='ingredient_tags', to='meal.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='categories',
            field=models.ManyToManyField(related_name='meal_categories', to='meal.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='devices',
            field=models.ManyToManyField(related_name='meal_devices', to='meal.device', verbose_name='Devices'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='meal_ingredients', to='meal.ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(related_name='meal_tags', to='meal.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='usermealingredient',
            name='categories',
            field=models.ManyToManyField(related_name='umi_categories', to='meal.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='usermealingredient',
            name='devices',
            field=models.ManyToManyField(related_name='umi_devices', to='meal.device', verbose_name='Devices'),
        ),
        migrations.AlterField(
            model_name='usermealingredient',
            name='ingredients',
            field=models.ManyToManyField(related_name='umi_ingredients', to='meal.ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='usermealingredient',
            name='meals',
            field=models.ManyToManyField(related_name='umi_meals', to='meal.meal', verbose_name='Meals'),
        ),
        migrations.AlterField(
            model_name='usermealingredient',
            name='tags',
            field=models.ManyToManyField(related_name='umi_tags', to='meal.tag', verbose_name='Tags'),
        ),
    ]
