# Generated by Django 5.0.2 on 2024-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_device_image_alter_ingredient_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('Popular', 'Popular'), ('Arab', 'Arab'), ('Indian', 'Indian')], max_length=20, null=True, verbose_name='Meal type'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Candy', 'Candy'), ('Drinks', 'Drinks')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='meal',
            name='category_type',
            field=models.CharField(blank=True, choices=[('cozen', 'Cozen'), ('calender', 'Calender'), ('healthy', 'Healthy')], max_length=20, null=True, verbose_name='Category type'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('Popular', 'Popular'), ('Arab', 'Arab'), ('Indian', 'Indian')], max_length=20, null=True, verbose_name='Meal type'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Candy', 'Candy'), ('Drinks', 'Drinks')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
