# Generated by Django 5.0.2 on 2024-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_ingredient_meal_type_ingredient_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category_type',
            field=models.CharField(blank=True, choices=[('cozen', 'Cozen'), ('calender', 'Calender'), ('healthy', 'Healthy')], max_length=20, null=True, verbose_name='Category type'),
        ),
    ]
