# Generated by Django 5.0.2 on 2024-03-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_ingredient_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
