# Generated by Django 5.0.2 on 2024-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_alter_usermealingredient_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermealingredient',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='umi_categories', to='meal.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='usermealingredient',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='umi_ingredients', to='meal.ingredient', verbose_name='Ingredients'),
        ),
    ]
