# Generated by Django 5.0.2 on 2024-03-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_alter_usermealingredient_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermealingredient',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='umi_categories', to='meal.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='usermealingredient',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, related_name='umi_devices', to='meal.device', verbose_name='Devices'),
        ),
        migrations.AlterField(
            model_name='usermealingredient',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='umi_ingredients', to='meal.ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='usermealingredient',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='umi_tags', to='meal.tag', verbose_name='Tags'),
        ),
    ]
