# Generated by Django 5.0.2 on 2024-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0010_alter_usermealingredient_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermealingredient',
            name='devices',
        ),
        migrations.AddField(
            model_name='usermealingredient',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Cozen', 'Cozen'), ('Calender', 'Calender'), ('Healthy', 'Healthy')], max_length=20, null=True, verbose_name='Category type'),
        ),
        migrations.AddField(
            model_name='usermealingredient',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('Popular', 'Popular'), ('Arab', 'Arab'), ('Indian', 'Indian')], max_length=20, null=True, verbose_name='Meal type'),
        ),
        migrations.AddField(
            model_name='usermealingredient',
            name='type',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Candy', 'Candy'), ('Drinks', 'Drinks')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Cozen', 'Cozen'), ('Calender', 'Calender'), ('Healthy', 'Healthy')], max_length=20, null=True, verbose_name='Category type'),
        ),
    ]
