# Generated by Django 5.0.2 on 2024-03-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0011_remove_usermealingredient_devices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermealingredient',
            name='tags',
        ),
    ]
