# Generated by Django 5.0.2 on 2024-03-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0012_remove_usermealingredient_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/categories', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/devices', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/ingredients', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/meals', verbose_name='Image'),
        ),
    ]
