# Generated by Django 5.0 on 2024-03-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0013_alter_category_image_alter_device_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
