# Generated by Django 5.0.2 on 2024-03-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0014_remove_meal_tags_remove_ingredient_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Cozen', 'Cozen'), ('Calender', 'Calender'), ('Healthy', 'Healthy')], max_length=20, null=True, verbose_name='Category type'),
        ),
    ]
