# Generated by Django 5.0.2 on 2024-03-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0015_alter_ingredient_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
