# Generated by Django 5.0.2 on 2024-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0016_remove_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredient_categories', to='meal.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='meal_categories', to='meal.category', verbose_name='Categories'),
        ),
    ]
