# Generated by Django 5.0.2 on 2024-03-27 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0017_alter_ingredient_categories_alter_meal_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Video'),
        ),
    ]
