# Generated by Django 5.0.2 on 2024-03-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0020_alter_meal_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='video',
        ),
    ]
