# Generated by Django 5.0.2 on 2024-03-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0022_meal_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='healthy_type',
            field=models.CharField(blank=True, choices=[('DIET', 'DIET'), ('KETO', 'KETO')], max_length=20, null=True, verbose_name='Healthy type'),
        ),
    ]
